#testmsg
test:
    msg: yyysssyyy
# Server
server:
    port: 9999
    tomcat:
        uri-encoding: UTF-8
        
# Mybatis  

mybatis:
    typeAliasesPackage: com.qkz5.oaattendance.entity.pojo
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis_config.xml
  
#log  
logging:
    level:
        org:
            springframework:
                web: INFO
        com:
            ibatis: DEBUG
#api gateway (develop)  
#-------------------------- 
############api.gateway.server=http://10.36.134.62:9002
#--------------------------  
  
#api gateway (test)  
#api.gateway.server=http://10.37.149.160:9102  
  
  
# mysql (test) 
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        #url:jdbc:mysql://localhost:3306/kaoqin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
        url: jdbc:mysql://39.105.63.82:3306/kaoqin?characterEncoding=utf8
        username: root
        password: Admin@123
        initialSize: 1
        minIdle: 1
        maxActive: 200
  
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true


    mybatis:
        mapperPackage: /mapper/*.xml
        dialect: MYSQL
#-----------------------------------  
  # REDIS (RedisProperties)

    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 39.105.63.82
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        pool:
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池中的最小空闲连接
            min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 5000

redis:
    # 数据的默认保存有效时间
    validDay: 1